name: Quote Generator

on:
  schedule:
    # Runs every 5 minutes, as GitHub Actions cannot run more frequently
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate quote
      
        env:
           APIKEY: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          # Start a background job to sleep for 10 seconds
          (
            sleep 10
            echo "Timeout reached. Exiting the job."
            exit 1
          ) &
          
          # Run your main script
          node index.js
          
          # Wait for the background timeout job to finish
          wait
